POST http://localhost:4000/api/user/register
Content-Type: application/json

{
  "firstName": "ducanh",
  "lastName": "nguyen",
  "username": "ducanh",
  "password": "123456"
}

###
POST http://localhost:4000/api/user/login
Content-Type: application/json

{
  "username": "ducanh",
  "password": "123456"
}

###
POST http://localhost:4000/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJpYXQiOjE2MzI4ODIwNzV9.cSTitCHiqrEpYP7kaBnih7W3ct6R7BKNlSE-2tCairU

{
  "name": "product 2",
  "amount": 20,
  "price": 500000,
  "des": "Description 2"
}

###
GET http://localhost:4000/api/product/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJpYXQiOjE2MzI4ODIwNzV9.cSTitCHiqrEpYP7kaBnih7W3ct6R7BKNlSE-2tCairU

###
GET http://localhost:4000/api/product/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJpYXQiOjE2MzI4ODIwNzV9.cSTitCHiqrEpYP7kaBnih7W3ct6R7BKNlSE-2tCairU

###
POST http://localhost:4000/api/product/find/name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJpYXQiOjE2MzI4ODIwNzV9.cSTitCHiqrEpYP7kaBnih7W3ct6R7BKNlSE-2tCairU

{
  "name": "p"
}

###
POST http://localhost:4000/api/product/update/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJpYXQiOjE2MzI4ODIwNzV9.cSTitCHiqrEpYP7kaBnih7W3ct6R7BKNlSE-2tCairU

{
  "name": "product 4 updated",
  "amount": 16,
  "price": 300000,
  "des": "Description 4 updated",
  "img": "image2.png"
}

###
DELETE http://localhost:4000/api/product/delete/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJpYXQiOjE2MzI4ODIwNzV9.cSTitCHiqrEpYP7kaBnih7W3ct6R7BKNlSE-2tCairU
